"""Session JSONL → REPORT.md.

Consumes the JSONL log written by session.py and produces a human-readable
Markdown report in the same session folder (sessions/<UTC>/REPORT.md).
One report per one-shot session — in REPL mode where each accepted line
spawns a fresh session folder, each objective produces its own
session.jsonl + REPORT.md pair under its own folder.

The report is best-effort: any failure while reading or rendering the
log falls through to a stub with the error message. Never raises to the
caller.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

# Match the first line of a formatted HTTP tool_result (see tools.py::
# _format_http). Example first lines:
#   "HTTP 200 OK"
#   "HTTP 301 Moved Permanently"
#   "HTTP 404 Not Found"
# followed on the next line by "URL: <url>".
_HTTP_STATUS_RE = re.compile(r"^HTTP\s+(\d{3})\s+", re.MULTILINE)
_HTTP_URL_RE = re.compile(r"^URL:\s*(\S+)", re.MULTILINE)


def write_report(session_jsonl: Path | str) -> Path:
    """Read a session JSONL and write REPORT.md in the same folder.
    Returns the path to the report file."""
    path = Path(session_jsonl)
    report_path = path.parent / "REPORT.md"
    try:
        events = _load(path)
        md = _render(events, session_name=path.name,
                     session_id=path.parent.name)
    except Exception as e:
        md = (f"# Bughunter Harness Lite — Session Report\n\n"
              f"Failed to build the report from `{path.name}`: "
              f"{type(e).__name__}: {e}\n")
    report_path.write_text(md, encoding="utf-8")
    return report_path


# ── internals ────────────────────────────────────────────────────────
def _load(path: Path) -> list[dict[str, Any]]:
    events: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                events.append(json.loads(line))
            except Exception:
                # Malformed line — skip. Better half a report than none.
                continue
    return events


def _last(events: list[dict], event_type: str) -> dict | None:
    match = None
    for e in events:
        if e.get("t") == event_type:
            match = e
    return match


def _short(s: str, n: int) -> str:
    s = (s or "").replace("\r", " ").replace("\n", " ").strip()
    return s if len(s) <= n else s[:n] + "…"


def _md_cell(s: str) -> str:
    """Escape a string for use inside a Markdown table cell."""
    return s.replace("|", "\\|")


def _classify_http(tool_results: list[dict]) -> dict[str, list[tuple[str, int]]]:
    """Walk every tool_result whose payload starts with an HTTP status line
    (i.e. came from http_get / http_post via tools._format_http). Group
    the (URL, status) pairs into 5 buckets: 200s, 401/403, 301/302, 404,
    other. Deduplicate URLs within each bucket keeping the first status
    seen (order = call order). Returns:

        {
          "200":   [(url, code), ...],
          "auth":  [(url, code), ...],   # 401 & 403
          "3xx":   [(url, code), ...],   # 301 & 302
          "404":   [(url, code), ...],
          "other": [(url, code), ...],   # 5xx, 429, etc.
        }
    """
    buckets: dict[str, list[tuple[str, int]]] = {
        "200": [], "auth": [], "3xx": [], "404": [], "other": [],
    }
    seen: set[str] = set()
    for tr in tool_results:
        name = tr.get("name", "")
        if name not in ("http_get", "http_post"):
            continue
        result = tr.get("result", "") or ""
        m_status = _HTTP_STATUS_RE.search(result)
        m_url = _HTTP_URL_RE.search(result)
        if not m_status or not m_url:
            continue
        code = int(m_status.group(1))
        url = m_url.group(1).strip()
        if url in seen:
            continue
        seen.add(url)
        if 200 <= code < 300:
            buckets["200"].append((url, code))
        elif code in (401, 403):
            buckets["auth"].append((url, code))
        elif code in (301, 302):
            buckets["3xx"].append((url, code))
        elif code == 404:
            buckets["404"].append((url, code))
        else:
            buckets["other"].append((url, code))
    return buckets


def _render_classification(buckets: dict[str, list[tuple[str, int]]]) -> str:
    """Render the auto-classification section as Markdown. Empty buckets
    print as '_(none)_' so a reader can tell 'nothing found' apart from
    'section missing'."""
    def _lines(entries: list[tuple[str, int]]) -> str:
        if not entries:
            return "_(none)_"
        return "\n".join(f"- {url} → {code}" for url, code in entries)

    return (
        "## Auto-classified by HTTP status (from raw tool_result events)\n"
        "\n"
        "Deterministic classification parsed directly from the "
        "`tool_result` events — this section is generated by the harness, "
        "not by the LLM, so it is always accurate. If it disagrees with "
        "the `## Findings` block below, trust THIS section.\n"
        "\n"
        "### 200 OK (path exists and is publicly readable)\n"
        f"{_lines(buckets['200'])}\n"
        "\n"
        "### 401 / 403 (path EXISTS but is protected — real fingerprint signal)\n"
        f"{_lines(buckets['auth'])}\n"
        "\n"
        "### 301 / 302 (redirect — often a framework catch-all with no signal)\n"
        f"{_lines(buckets['3xx'])}\n"
        "\n"
        "### 404 (path does NOT exist — safe to ignore)\n"
        f"{_lines(buckets['404'])}\n"
        "\n"
        "### Other HTTP statuses (5xx, 429, 418, ...)\n"
        f"{_lines(buckets['other'])}\n"
    )


def _render(events: list[dict], session_name: str,
            session_id: str = "") -> str:
    meta = _last(events, "meta") or {}
    end = _last(events, "end") or {}
    finish = _last(events, "finish") or {}
    kill = _last(events, "kill") or {}
    sigint = _last(events, "sigint")

    cfg = meta.get("config") or {}
    scope = cfg.get("scope") or {}

    objective = meta.get("objective") or "(none)"
    started = meta.get("ts") or ""
    ended = end.get("ts") or ""
    iters = end.get("iterations", 0)
    elapsed = end.get("elapsed_sec", 0)

    tool_calls = [e for e in events if e.get("t") == "tool_call"]
    tool_results = [e for e in events if e.get("t") == "tool_result"]
    llm_replies = [e for e in events if e.get("t") == "llm_reply"]

    if finish:
        outcome = "finish"
        outcome_note = finish.get("summary") or "(empty summary)"
    elif sigint:
        outcome = "sigint"
        outcome_note = "user interrupted with Ctrl+C"
    elif kill:
        outcome = "kill"
        outcome_note = kill.get("reason") or "(unknown reason)"
    else:
        outcome = "incomplete"
        outcome_note = "(session ended without finish/kill/sigint marker)"

    lines: list[str] = []
    lines.append("# Bughunter Harness Lite — Session Report")
    lines.append("")

    # Header block
    if session_id:
        lines.append(f"- **Session ID**: `{session_id}`")
    lines.append(f"- **Session log**: `{session_name}` "
                 f"(in the same folder as this report)")
    lines.append(f"- **Objective**: {_short(objective, 400)}")
    lines.append(f"- **Backend**: {cfg.get('backend', '?')} · "
                 f"model `{cfg.get('model', '?')}`")
    if cfg.get("base_url"):
        lines.append(f"- **Base URL**: `{cfg['base_url']}`")
    lines.append(
        f"- **Scope**: "
        f"hosts={scope.get('hosts', [])} · "
        f"wildcards={scope.get('wildcards', [])} · "
        f"networks={scope.get('networks', [])}"
    )
    if cfg.get("oob_host"):
        lines.append(f"- **OOB**: {cfg['oob_host']} · "
                     f"prefix `{cfg.get('oob_token_prefix', 'lite')}`")
    lines.append(f"- **Started**: {started}")
    lines.append(f"- **Ended**: {ended} · "
                 f"{elapsed}s elapsed · {iters} iterations · "
                 f"{len(tool_calls)} tool calls")
    lines.append(f"- **Outcome**: `{outcome}` — {_short(outcome_note, 400)}")
    lines.append("")

    # Tool call timeline
    lines.append("## Tool calls (timeline)")
    lines.append("")
    if not tool_calls:
        lines.append("_(none)_")
    else:
        lines.append("| # | Tool | Args | Result (first 120 chars) |")
        lines.append("|---|------|------|--------------------------|")
        for i, tc in enumerate(tool_calls, 1):
            args_short = _short(json.dumps(tc.get("args") or {},
                                          ensure_ascii=False), 60)
            res = (tool_results[i - 1].get("result", "")
                   if i - 1 < len(tool_results) else "")
            res_short = _short(res, 120)
            lines.append(
                f"| {i} | `{_md_cell(tc.get('name', '?'))}` | "
                f"`{_md_cell(args_short)}` | "
                f"`{_md_cell(res_short)}` |"
            )
    lines.append("")

    # Auto-classification by HTTP status — deterministic, harness-generated.
    # Comes BEFORE the LLM-authored Findings so a reader sees the honest
    # data first. Small models regularly mis-classify paths (e.g. writing
    # a 403 URL under "Paths 200 OK") — this section is the ground truth.
    buckets = _classify_http(tool_results)
    if any(buckets.values()):
        lines.append(_render_classification(buckets))
        lines.append("")

    # Assistant narrative — the free-text content of any LLM reply that
    # also carried words (models often speak only through tool_calls, in
    # which case this section is empty).
    narratives = [(i + 1, r.get("content", "")) for i, r in enumerate(llm_replies)
                  if (r.get("content") or "").strip()]
    lines.append("## Assistant narrative")
    lines.append("")
    if not narratives:
        lines.append("_(model spoke only through tool calls — no free text)_")
    else:
        for turn, txt in narratives:
            lines.append(f"### Turn {turn}")
            lines.append("")
            lines.append(txt.rstrip())
            lines.append("")

    # Findings — parsed from the finish() summary (or the kill reason if
    # the session did not finish cleanly). Explicit hallucination warning
    # so a reader knows this block is untrusted; the deterministic
    # classification above is the ground truth.
    lines.append("## Findings (LLM summary — may contain hallucinations)")
    lines.append("")
    lines.append(
        "> Small models (3B–7B) sometimes invent server versions or "
        "mis-classify paths in this block. Cross-check every claim "
        "against the `Auto-classified by HTTP status` section above and "
        "against the raw `tool_result` events in `session.jsonl` before "
        "treating anything here as a real finding."
    )
    lines.append("")
    if finish and finish.get("summary"):
        lines.append(finish["summary"])
    elif kill:
        lines.append(f"_Session killed before finish(): {_short(outcome_note, 400)}_")
    elif sigint:
        lines.append("_Session interrupted with Ctrl+C._")
    else:
        lines.append("_Session ended without finish() — no findings recorded._")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(f"Full event log: `{session_name}` "
                 f"({len(events)} events, JSONL format).")
    lines.append("")
    return "\n".join(lines)
